### PR TITLE
Optional, more compact deriving clause formatting (part 2)

### PR DESCRIPTION
**Pull request by tchoutri**
*(This PR supersedes #313)*

### TODO

* [ ] Write tests

This PR aims to make the newline-prefixed deriving clauses rendering optional, by introducing a, respectively option and constructor, `deriving_same_line` and `cDerivingSameLine`, and additional logic to enable either rendering.

With that option enabled, the (default) behaviour of :

```haskell
data TestRecord                 
  = TestRecord { top    :: Int   
               , bottom :: String
               }                 
  deriving (Show)  -- ← `deriving` clause is put on a separate new line
```
would be turned into

```haskell
data TestRecord                  
  = TestRecord { top    :: Int   
               , bottom :: String
               } deriving (Show)          
```

Which is more compact and in line with the style of many Haskell code-bases.

That behaviour would only be considered on single-deriving clause records. 

---
Closes https://github.com/jaspervdj/stylish-haskell/issues/308

### CODE REVIEW

**Comment by EncodePanda** [comment]
Cool, thanks for working on this. Do you need any help, anything blocking you?

**Comment by tchoutri** [comment]
Hi @EncodePanda! Yes I would require some help to understand the AST tranformations. I would love to pair with someone who has more understanding of it all than me. :)

**Comment by EncodePanda** [comment]
I know a bit, but not much. I'm more than happy to do pair programming. I will reach out via DM on LinkedIn.

**Comment by tysonzero** [comment]
Big fan of this!

It would be nice to also allow for:

```
data Foo = Foo
    { bar :: Int
    , baz :: Bool
    } deriving stock (Eq, Show, Generic)
      deriving anyclass (FromJSON)
```

**Comment by tchoutri** [comment]
@tysonzero Unfortunately I am unable to keep working on it at present time. :(
You'll have to take the flame from my hands if you want to see this done.

**Comment by tysonzero** [comment]
@tchoutri Fair enough! For now if this could get merged as is that'd be super useful!

**Comment by tchoutri** [comment]
@tysonzero It unfortunately isn't mergeable as it is. :/

**Pull request closed without merging**
