### PR TITLE
Support ghc-9.4

### PR DESCRIPTION
**Pull request by July541**

### CODE REVIEW

**Comment by July541** [comment]
It is only buildable with ghc-lib, build with ghc-9.4 requires to specify flag for ghc-lib-parser-ex...

**Comment by July541** [comment]
Slightly ping @jaspervdj, any update required here?

**Comment by jaspervdj** [comment]
Looks good to me, thanks a lot for taking this on!

**Review by jaspervdj — APPROVED** [review]

**Comment by michaelpj** [comment]
It would be great to get a release with this in, I think that's all that's stopping us supporting stylish-haskell for 9.4 in HLS.

**Comment by EncodePanda** [comment]
@jaspervdj I think we can cut a release, correct?

**Pull request merged**
