### PR TITLE
Update to support GHC 9.6

### LINKED ISSUE #458: GHC 9.6 support
It's been out for a little while. I was able to get the dependencies sorted and fix a couple of compile errors, but there are more. WIP branch [here](https://github.com/michaelpj/stylish-haskell/tree/mpj/9.6-support) if anyone else feels motivated, otherwise perhaps I will get back to it.

### PR DESCRIPTION
**Pull request by michaelpj**
Fixes #458

### CODE REVIEW

**Comment by michaelpj** [comment]
Hmm, looks like the latest `ghc-lib-parser` doesn't support 9.0. I'm not sure what to do about that: AFAICT that's their intended support policy, and to do anything else we'd need to add a bunch of CPP, which is exactly what we're avoiding with `ghc-lib-parser`. So maybe it's just time to drop 9.0?

**Comment by michaelpj** [comment]
I added 9.6 to the workflow and removed 9.0, but it probably won't run since my PR is from a fork.

**Review by jaspervdj — APPROVED** [review]
Looks good!  I was about to bump `optparse-applicative` in another PR, thanks for taking care of that as well!

**Comment by michaelpj** [comment]
Yeah, I'm just trying to make stack happy...

**Comment by michaelpj** [comment]
Okay, it's all green!

**Comment by jaspervdj** [comment]
Thanks a lot!

**Comment by michaelpj** [comment]
It would be great to get a release, then we can get this supported in HLS.

**Comment by jaspervdj** [comment]
Released as v0.14.5.0

**Comment by michaelpj** [comment]
Thanks, I've made a PR to enable it in HLS :)

**Pull request merged**
