### PR TITLE
Add support for post qualified import formatting (more cases)

### LINKED ISSUE #334: Format imports qualified post
Starting from GHC 8.10, with this extension enabled, one can write:

```haskell
import A qualified
import B
import C
```

Now we can save 10 spaces on non-qualified imports!

```haskell
module Bad where

import Control.Applicative ((<$>))
import System.Directory    (doesFileExist)

import Data.Map            (Map, keys, (!))
import Data.Map            qualified as M
```

### PR DESCRIPTION
**Pull request by akrmn**
Based on the work started by @jhmcstanton. I added a few more test cases, and adapted the logic to support them. I originally submitted this as a PR to @jhmcstanton's branch, but I haven't got a reply, so I thought submitting a PR including their commit might be simpler.

Adds an option to use post qualified module imports.

Related to #284
Resolves #334
Improves on #335 

Let me know if any more tests or changes are needed.

### CODE REVIEW

**Review by lukasz-golebiewski — APPROVED** [review]
Looks great, thanks!

**Comment by cblp** [comment]
Could you please release this change?

**Comment by lukasz-golebiewski** [comment]
@jaspervdj could you?

**Comment by jaspervdj** [comment]
Released `v0.13.0.0` :confetti_ball:

**Comment by cblp** [comment]
❤️

**Pull request merged**
