### PR TITLE
9.8 support

### PR DESCRIPTION
**Pull request by michaelpj**
Work-in-progress. I did the obvious changes. There are a few test failures in the language pragma tests and I don't know why, otherwise it seems to work.

### CODE REVIEW

**Comment by michaelpj** [comment]
Ah, so taking the new `ghc-lib-parser` will force us to drop 9.2. I don't know if that's okay.

**Comment by michaelpj** [comment]
Okay, I'm fairly confused, I've traced this back to the exactprint annotations for the module not containing the `ViewPatterns` pragma, which is baffling.

**Comment by michaelpj** [comment]
I tracked it down. It seems that if you don't provide a `module X where` header, then something goes wrong with the attaching of the exactprint annotations (`moduleLanguagePragmas` does not produce the right comments, and printing out the annotations confirms that). What seems to happen is:
```
{-# LANGUAGE P1 #-} 
{-# LANGUAGE P2 #-}
x = 1
```
then we see only the P1 comment attached to the module. Notably, this other case works:
```
{-# LANGUAGE P1 #-} 
{-# LANGUAGE P2 #-} 
```

My suspicion is that something has changed in the parser so maybe `pragma1; pragma2; binding` now parses as `pragma1; module; pragma2; binding` rather than `pragma1; pragma2; module; binding`.

Perhaps @alanz has an idea?

For now I've added module headers to the tests that were failing. I would like to add a known-failing test demonstrating the problem, but I don't know how to do that in the test framework.

**Comment by michaelpj** [comment]
Otherwise this is ready for review @jaspervdj

**Comment by michaelpj** [comment]
Probable GHC issue: https://gitlab.haskell.org/ghc/ghc/-/issues/23984

**Comment by alanz** [comment]
I just added a test with

```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
x = 1
```
To the ghc-exactprint  ghc-9.8 branch, and it passes.

The original example with `P1` and `P2` fails, because the pragma-extraction step errors with unknown pragmas.

I will be preparing a ghc-9.8.1 release this evening.

**Comment by michaelpj** [comment]
Alan, I'm confused about how this ends up working for `stylish-haskell`. It depends on `ghc-lib-parser`, which is based on the GHC sources. I don't think it uses `ghc-exactprint` at all...

**Comment by alanz** [comment]
@michaelpj I have no idea how stylish haskell works.  But if it does not use ghc-exactprint, then it may have to do something like https://github.com/alanz/ghc-exactprint/blob/master/src/Language/Haskell/GHC/ExactPrint/Parsers.hs#L303

**Comment by michaelpj** [comment]
ping @jaspervdj ?

**Review by jaspervdj — APPROVED** [review]
Changes look good to me.  I would like to fix the module header issue, but I can do that separately as a follow-up if you want a release of this soon (e.g. for HLS)?

**Comment by jaspervdj** [comment]
After reading through the comments and the GHC ticket more carefully, it's clear to me that fixing this downstream is probably more trouble than it's worth.  I will add one test case using an empty line rather than `module Main where` since I think that's more common in short `.hs` files.

**Comment by michaelpj** [comment]
Thanks!

Would it be possible to get a release too?

**Comment by jaspervdj** [comment]
Released as `v0.14.6.0`.  Thanks again for the GHC 9.8 PR!

**Pull request merged**
